---
- hosts: all
  remote_user: root
  vars:
    setup_user:
      name: ansibleuser
      pubkey: "{{ lookup('env','ANSIBLE_PUBKEY') }}" #ANSIBLE_PUBKEY 環境変数から設定する
  roles:
    - role: ansible-user-setup

